spring.application.name=ORDER-SERVICE

# MongoDB Configuration
spring.mongodb.uri=mongodb+srv://Akila:akila@posorder.9a3ldvy.mongodb.net/posApp?retryWrites=true&w=majority&appName=PosOrder

# Server Configuration
server.port=8083

# Eureka Configuration
eureka.client.service-url.defaultZone=https://ctseserviceregistryapp.purplecoast-1718a0fd.centralindia.azurecontainerapps.io/eureka/
eureka.instance.prefer-ip-address=true

# Inventory Service Discovery
inventory.service.name=INVENTORY-SERVICE
inventory.service.product-path=/api/inventory/{productId}
